name: "reverse_string_pstr"
limit: 1000
memory_size: 0x120
input_streams:
  0x80: [5, 72, 101, 108, 108, 111]
  0x84: []
reports:
  - name: Step-by-step
    slice: all
    view: |
      {pc}:	{instruction}	{pc:label}
      A B T S R
      {A:dec} {B:dec} {T:dec} {S:dec} {R}

      STACK
      {stack:dec}

  - name: Result
    slice: last
    filter:
      - state
    view: |
      numio[0x80]: {io:0x80:dec}
      numio[0x84]: {io:0x84:dec}
    assert: |
      numio[0x80]: [] >>> []
      numio[0x84]: [] >>> [5,111,108,108,101,72] 
